name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-mock

      - name: Run unit tests and generate JUnit report
        run: pytest -v tests/ --junitxml=pytest-results.xml

      - name: Upload test results to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: pytest-results.xml

